#pragma once

#define M_PI		3.14159265358979323846f
#define M_RADPI		57.295779513082f
#define RAD2DEG(x)  (static_cast<float>(x) * static_cast<float>(180.f / M_PI))
#define DEG2RAD(x)  (static_cast<float>(x) * static_cast<float>(M_PI / 180.f))

#define IN_RANGE(a, b, c)		(a >= b && a <= c) 

#define TICK_INTERVAL			(interfaces::global_vars->m_interval_per_tick)

#define TIME_TO_TICKS(dt)		(static_cast<int>(0.5f + static_cast<float>(dt) / TICK_INTERVAL))
#define TICKS_TO_TIME(t)		(TICK_INTERVAL * (t))
#define ROUND_TO_TICKS(t)		(TICK_INTERVAL * TIME_TO_TICKS(t))

#define NUM_ENT_ENTRY_BITS				(11 + 2)
#define NUM_ENT_ENTRIES					(1 << NUM_ENT_ENTRY_BITS)
#define INVALID_EHANDLE_INDEX			0xFFFFFFFF
#define NUM_SERIAL_NUM_BITS				16
#define NUM_SERIAL_NUM_SHIFT_BITS		(32 - NUM_SERIAL_NUM_BITS)
#define ENT_ENTRY_MASK					((1 << NUM_SERIAL_NUM_BITS) - 1)

#define DECL_ALIGN(x)			__declspec(align(x))

#define ALIGN4 DECL_ALIGN(4)
#define ALIGN8 DECL_ALIGN(8)
#define ALIGN16 DECL_ALIGN(16)
#define ALIGN32 DECL_ALIGN(32)
#define ALIGN128 DECL_ALIGN(128)

#define MAX_COORD_FLOAT (16384.0f)
#define MIN_COORD_FLOAT (-MAX_COORD_FLOAT)

#define EVENT_DEBUG_ID_INIT 42
#define EVENT_DEBUG_ID_SHUTDOWN 13

#define MULTIPLAYER_BACKUP				150

#define DISPSURF_FLAG_SURFACE           (1 << 0)
#define DISPSURF_FLAG_WALKABLE          (1 << 1)
#define DISPSURF_FLAG_BUILDABLE         (1 << 2)
#define DISPSURF_FLAG_SURFPROP1         (1 << 3)
#define DISPSURF_FLAG_SURFPROP2         (1 << 4)

#define HITGROUP_GENERIC  0
#define HITGROUP_HEAD     1
#define HITGROUP_CHEST    2
#define HITGROUP_STOMACH  3
#define HITGROUP_LEFTARM  4    
#define HITGROUP_RIGHTARM 5
#define HITGROUP_LEFTLEG  6
#define HITGROUP_RIGHTLEG 7
#define HITGROUP_GEAR    10

#define HITBOX_HEAD					0
#define HITBOX_NECK					1
#define HITBOX_PELVIS				2
#define HITBOX_STOMACH				3
#define HITBOX_LOWER_CHEST			4
#define HITBOX_CHEST				5
#define HITBOX_UPPER_CHEST			6
#define HITBOX_RIGHT_THIGH			7
#define HITBOX_LEFT_THIGH			8
#define HITBOX_RIGHT_SHIN			9
#define HITBOX_LEFT_SHIN			10
#define HITBOX_RIGHT_FOOT			11
#define HITBOX_LEFT_FOOT			12
#define HITBOX_RIGHT_HAND			13
#define HITBOX_LEFT_HAND			14
#define HITBOX_RIGHT_UPPER_ARM		15
#define HITBOX_RIGHT_LOWER_ARM		16
#define HITBOX_LEFT_UPPER_ARM		17
#define HITBOX_LEFT_LOWER_ARM		18
#define HITBOX_MAX					19

#define TEXTURE_GROUP_LIGHTMAP						"Lightmaps"
#define TEXTURE_GROUP_WORLD							"World textures"
#define TEXTURE_GROUP_MODEL							"Model textures"
#define TEXTURE_GROUP_VGUI							"VGUI textures"
#define TEXTURE_GROUP_PARTICLE						"Particle textures"
#define TEXTURE_GROUP_DECAL							"Decal textures"
#define TEXTURE_GROUP_SKYBOX						"SkyBox textures"
#define TEXTURE_GROUP_CLIENT_EFFECTS				"ClientEffect textures"
#define TEXTURE_GROUP_OTHER							"Other textures"
#define TEXTURE_GROUP_PRECACHED						"Precached"
#define TEXTURE_GROUP_CUBE_MAP						"CubeMap textures"
#define TEXTURE_GROUP_RENDER_TARGET					"RenderTargets"
#define TEXTURE_GROUP_UNACCOUNTED					"Unaccounted textures"
#define TEXTURE_GROUP_STATIC_PROP					"StaticProp textures"
#define TEXTURE_GROUP_STATIC_INDEX_BUFFER			"Static Indices"
#define TEXTURE_GROUP_STATIC_VERTEX_BUFFER_DISP		"Displacement Verts"
#define TEXTURE_GROUP_STATIC_VERTEX_BUFFER_COLOR	"Lighting Verts"
#define TEXTURE_GROUP_STATIC_VERTEX_BUFFER_WORLD	"World Verts"
#define TEXTURE_GROUP_STATIC_VERTEX_BUFFER_MODELS	"Model Verts"
#define TEXTURE_GROUP_STATIC_VERTEX_BUFFER_OTHER	"Other Verts"
#define TEXTURE_GROUP_DYNAMIC_INDEX_BUFFER			"Dynamic Indices"
#define TEXTURE_GROUP_DYNAMIC_VERTEX_BUFFER			"Dynamic Verts"
#define TEXTURE_GROUP_DEPTH_BUFFER					"DepthBuffer"
#define TEXTURE_GROUP_VIEW_MODEL					"ViewModel"
#define TEXTURE_GROUP_PIXEL_SHADERS					"Pixel Shaders"
#define TEXTURE_GROUP_VERTEX_SHADERS				"Vertex Shaders"
#define TEXTURE_GROUP_RENDER_TARGET_SURFACE			"RenderTarget Surfaces"
#define TEXTURE_GROUP_MORPH_TARGETS					"Morph Targets"

#define FCVAR_UNREGISTERED				(1 << 0)
#define FCVAR_DEVELOPMENTONLY			(1 << 1)
#define FCVAR_GAMEDLL					(1 << 2)
#define FCVAR_CLIENTDLL					(1 << 3)
#define FCVAR_HIDDEN					(1 << 4)

#define FCVAR_PROTECTED					(1 << 5)
#define FCVAR_SPONLY					(1 << 6)
#define	FCVAR_ARCHIVE					(1 << 7)
#define	FCVAR_NOTIFY					(1 << 8)
#define	FCVAR_USERINFO					(1 << 9)
#define FCVAR_CHEAT						(1 << 14)

#define FCVAR_PRINTABLEONLY				(1 << 10)
#define FCVAR_UNLOGGED					(1 << 11)
#define FCVAR_NEVER_AS_STRING			(1 << 12)

#define FCVAR_REPLICATED				(1 << 13)
#define FCVAR_DEMO						(1 << 16)
#define FCVAR_DONTRECORD				(1 << 17)
#define FCVAR_RELOAD_MATERIALS			(1 << 20)
#define FCVAR_RELOAD_TEXTURES			(1 << 21)

#define FCVAR_NOT_CONNECTED				(1 << 22)
#define FCVAR_MATERIAL_SYSTEM_THREAD	(1 << 23)
#define FCVAR_ARCHIVE_XBOX				(1 << 24) 

#define FCVAR_ACCESSIBLE_FROM_THREADS	(1 << 25)

#define FCVAR_SERVER_CAN_EXECUTE		(1 << 28)
#define FCVAR_SERVER_CANNOT_QUERY		(1 << 29)
#define FCVAR_CLIENTCMD_CAN_EXECUTE		(1 << 30)

#define FCVAR_MATERIAL_THREAD_MASK		(FCVAR_RELOAD_MATERIALS | FCVAR_RELOAD_TEXTURES | FCVAR_MATERIAL_SYSTEM_THREAD)	

#define FLOW_OUTGOING	0		
#define FLOW_INCOMING	1
#define MAX_FLOWS		2

#define DAMAGE_NO			        0
#define DAMAGE_EVENTS_ONLY	        1	
#define DAMAGE_YES					2
#define DAMAGE_AIM					3

#define BONE_CALCULATE_MASK			0x1F
#define BONE_PHYSICALLY_SIMULATED	0x01
#define BONE_PHYSICS_PROCEDURAL		0x02
#define BONE_ALWAYS_PROCEDURAL		0x04
#define BONE_SCREEN_ALIGN_SPHERE	0x08
#define BONE_SCREEN_ALIGN_CYLINDER	0x10

#define BONE_USED_BY_ANYTHING		0x0007FF00
#define BONE_USED_BY_HITBOX			0x00000100
#define BONE_USED_BY_ATTACHMENT		0x00000200
#define BONE_USED_BY_VERTEX_MASK	0x0003FC00
#define BONE_USED_BY_VERTEX_LOD0	0x00000400
#define BONE_USED_BY_VERTEX_LOD1	0x00000800	
#define BONE_USED_BY_VERTEX_LOD2	0x00001000  
#define BONE_USED_BY_VERTEX_LOD3	0x00002000
#define BONE_USED_BY_VERTEX_LOD4	0x00004000
#define BONE_USED_BY_VERTEX_LOD5	0x00008000
#define BONE_USED_BY_VERTEX_LOD6	0x00010000
#define BONE_USED_BY_VERTEX_LOD7	0x00020000
#define BONE_USED_BY_BONE_MERGE		0x00040000
#define BONE_ALWAYS_SETUP			0x00080000

#define STUDIO_PROC_AXISINTERP		1
#define STUDIO_PROC_QUATINTERP		2
#define STUDIO_PROC_AIMATBONE		3
#define STUDIO_PROC_AIMATATTACH		4
#define STUDIO_PROC_JIGGLE			5
#define STUDIO_PROC_TWIST_MASTER	6
#define STUDIO_PROC_TWIST_SLAVE		7

#define CHAR_TEX_CONCRETE	'C'	
#define CHAR_TEX_METAL		'M'
#define CHAR_TEX_DIRT		'D'
#define CHAR_TEX_VENT		'V'
#define CHAR_TEX_GRATE		'G'
#define CHAR_TEX_TILE		'T'
#define CHAR_TEX_SLOSH		'S'
#define CHAR_TEX_WOOD		'W'
#define CHAR_TEX_COMPUTER	'P'
#define CHAR_TEX_GLASS		'Y'
#define CHAR_TEX_FLESH		'F'
#define CHAR_TEX_SNOW		'N'
#define CHAR_TEX_PLASTIC	'L'
#define CHAR_TEX_CARDBOARD	'U'

#define	SURF_LIGHT		0x0001
#define	SURF_SKY2D		0x0002
#define	SURF_SKY		0x0004
#define	SURF_WARP		0x0008
#define	SURF_TRANS		0x0010
#define SURF_NOPORTAL	0x0020
#define	SURF_TRIGGER	0x0040
#define	SURF_NODRAW		0x0080

#define	SURF_HINT		0x0100

#define	SURF_SKIP		0x0200
#define SURF_NOLIGHT	0x0400
#define SURF_BUMPLIGHT	0x0800
#define SURF_NOSHADOWS	0x1000
#define SURF_NODECALS	0x2000
#define SURF_NOPAINT	SURF_NODECALS
#define SURF_NOCHOP		0x4000
#define SURF_HITBOX		0x8000

#define	CONTENTS_EMPTY					0

#define	CONTENTS_SOLID					0x1
#define	CONTENTS_WINDOW					0x2
#define	CONTENTS_AUX					0x4
#define	CONTENTS_GRATE					0x8
#define	CONTENTS_SLIME					0x10
#define	CONTENTS_WATER					0x20
#define	CONTENTS_BLOCKLOS				0x40
#define CONTENTS_OPAQUE					0x80
#define	LAST_VISIBLE_CONTENTS			CONTENTS_OPAQUE

#define ALL_VISIBLE_CONTENTS			(LAST_VISIBLE_CONTENTS | (LAST_VISIBLE_CONTENTS - 1))

#define CONTENTS_TESTFOGVOLUME			0x100
#define CONTENTS_UNUSED					0x200	

#define CONTENTS_BLOCKLIGHT				0x400

#define CONTENTS_TEAM1					0x800
#define CONTENTS_TEAM2					0x1000

#define CONTENTS_IGNORE_NODRAW_OPAQUE	0x2000

#define CONTENTS_MOVEABLE				0x4000

#define	CONTENTS_AREAPORTAL				0x8000

#define	CONTENTS_PLAYERCLIP				0x10000
#define	CONTENTS_MONSTERCLIP			0x20000

#define	CONTENTS_CURRENT_0				0x40000
#define	CONTENTS_CURRENT_90				0x80000
#define	CONTENTS_CURRENT_180			0x100000
#define	CONTENTS_CURRENT_270			0x200000
#define	CONTENTS_CURRENT_UP				0x400000
#define	CONTENTS_CURRENT_DOWN			0x800000

#define	CONTENTS_ORIGIN					0x1000000

#define	CONTENTS_MONSTER				0x2000000
#define	CONTENTS_DEBRIS					0x4000000
#define	CONTENTS_DETAIL					0x8000000
#define	CONTENTS_TRANSLUCENT			0x10000000
#define	CONTENTS_LADDER					0x20000000
#define CONTENTS_HITBOX					0x40000000

#define	MASK_ALL					(0xFFFFFFFF)
#define	MASK_SOLID					(CONTENTS_SOLID | CONTENTS_MOVEABLE | CONTENTS_WINDOW | CONTENTS_MONSTER | CONTENTS_GRATE)
#define	MASK_PLAYERSOLID			(CONTENTS_SOLID | CONTENTS_MOVEABLE | CONTENTS_PLAYERCLIP | CONTENTS_WINDOW | CONTENTS_MONSTER | CONTENTS_GRATE)
#define	MASK_NPCSOLID				(CONTENTS_SOLID | CONTENTS_MOVEABLE | CONTENTS_MONSTERCLIP | CONTENTS_WINDOW | CONTENTS_MONSTER | CONTENTS_GRATE)
#define	MASK_NPCFLUID				(CONTENTS_SOLID | CONTENTS_MOVEABLE | CONTENTS_MONSTERCLIP | CONTENTS_WINDOW | CONTENTS_MONSTER)
#define	MASK_WATER					(CONTENTS_WATER | CONTENTS_MOVEABLE | CONTENTS_SLIME)
#define	MASK_OPAQUE					(CONTENTS_SOLID | CONTENTS_MOVEABLE | CONTENTS_OPAQUE)
#define MASK_OPAQUE_AND_NPCS		(MASK_OPAQUE | CONTENTS_MONSTER)
#define MASK_BLOCKLOS				(CONTENTS_SOLID | CONTENTS_MOVEABLE | CONTENTS_BLOCKLOS)
#define MASK_BLOCKLOS_AND_NPCS		(MASK_BLOCKLOS | CONTENTS_MONSTER)
#define	MASK_VISIBLE				(MASK_OPAQUE | CONTENTS_IGNORE_NODRAW_OPAQUE)
#define MASK_VISIBLE_AND_NPCS		(MASK_OPAQUE_AND_NPCS | CONTENTS_IGNORE_NODRAW_OPAQUE)
#define	MASK_SHOT					(CONTENTS_SOLID | CONTENTS_MOVEABLE | CONTENTS_MONSTER | CONTENTS_WINDOW | CONTENTS_DEBRIS | CONTENTS_HITBOX)
#define MASK_SHOT_BRUSHONLY			(CONTENTS_SOLID | CONTENTS_MOVEABLE | CONTENTS_WINDOW | CONTENTS_DEBRIS)
#define MASK_SHOT_HULL				(CONTENTS_SOLID | CONTENTS_MOVEABLE | CONTENTS_MONSTER | CONTENTS_WINDOW | CONTENTS_DEBRIS | CONTENTS_GRATE)
#define MASK_SHOT_PORTAL			(CONTENTS_SOLID | CONTENTS_MOVEABLE | CONTENTS_WINDOW | CONTENTS_MONSTER)
#define MASK_SOLID_BRUSHONLY		(CONTENTS_SOLID | CONTENTS_MOVEABLE | CONTENTS_WINDOW | CONTENTS_GRATE)
#define MASK_PLAYERSOLID_BRUSHONLY	(CONTENTS_SOLID | CONTENTS_MOVEABLE | CONTENTS_WINDOW | CONTENTS_PLAYERCLIP | CONTENTS_GRATE)
#define MASK_NPCSOLID_BRUSHONLY		(CONTENTS_SOLID | CONTENTS_MOVEABLE | CONTENTS_WINDOW | CONTENTS_MONSTERCLIP | CONTENTS_GRATE)
#define MASK_NPCWORLDSTATIC			(CONTENTS_SOLID | CONTENTS_WINDOW | CONTENTS_MONSTERCLIP | CONTENTS_GRATE)
#define MASK_NPCWORLDSTATIC_FLUID	(CONTENTS_SOLID | CONTENTS_WINDOW | CONTENTS_MONSTERCLIP)
#define MASK_SPLITAREAPORTAL		(CONTENTS_WATER | CONTENTS_SLIME)
#define MASK_CURRENT				(CONTENTS_CURRENT_0 | CONTENTS_CURRENT_90 | CONTENTS_CURRENT_180 | CONTENTS_CURRENT_270 | CONTENTS_CURRENT_UP | CONTENTS_CURRENT_DOWN)
#define	MASK_DEADSOLID				(CONTENTS_SOLID | CONTENTS_PLAYERCLIP | CONTENTS_WINDOW | CONTENTS_GRATE)
#define	MASK_SHOT_PLAYER			(MASK_SHOT_HULL | CONTENTS_HITBOX)

#define MAX_PENETRATION_DISTANCE	90.f

#define CAM_HULL_OFFSET		14.0 
#define CAM_HULL_MIN		vec3_t(-CAM_HULL_OFFSET, -CAM_HULL_OFFSET, -CAM_HULL_OFFSET)
#define CAM_HULL_MAX		vec3_t(CAM_HULL_OFFSET, CAM_HULL_OFFSET, CAM_HULL_OFFSET)

#define IN_ATTACK        (1 << 0)
#define IN_JUMP          (1 << 1)
#define IN_DUCK          (1 << 2)
#define IN_FORWARD       (1 << 3)
#define IN_BACK          (1 << 4)
#define IN_USE           (1 << 5)
#define IN_CANCEL        (1 << 6)
#define IN_LEFT          (1 << 7)
#define IN_RIGHT         (1 << 8)
#define IN_MOVELEFT      (1 << 9)
#define IN_MOVERIGHT     (1 << 10)
#define IN_ATTACK2       (1 << 11)
#define IN_RUN           (1 << 12)
#define IN_RELOAD        (1 << 13)
#define IN_ALT1          (1 << 14)
#define IN_ALT2          (1 << 15)
#define IN_SCORE         (1 << 16)
#define IN_SPEED         (1 << 17)
#define IN_WALK          (1 << 18)
#define IN_ZOOM          (1 << 19)
#define IN_WEAPON1       (1 << 20)
#define IN_WEAPON2       (1 << 21)
#define IN_BULLRUSH      (1 << 22)
#define IN_GRENADE1      (1 << 23)
#define IN_GRENADE2      (1 << 24)
#define IN_ATTACK3       (1 << 25)

class c_animation_layer;

typedef std::array<float, 24> pose_params;
typedef std::array<c_animation_layer, 15> anim_layers;

double inline __declspec (naked) __fastcall fast_sqrt(double n) {
	_asm {
		fld qword ptr[esp + 4]
		fsqrt
		ret 8
	}
}
